### ISSUE TITLE
Better circle ci cache

### ISSUE THREAD

**Issue by PatelUtkarsh** [rtCamp/ci-demo#10]
Read: https://circleci.com/docs/2.0/caching/

We should be caching wp-cli, yarn / npm and composer dependency. 

- ~/.composer/cache
- ~/.wp-cli/cache
- ~/.yarn_cache
- ~/.npm

This all should have a separate cache block for storing and restoring it. and we should use their lock file or WP version file or static string depends on package for their cache key. 

Example: `restore_cache` should be above deploy task. 

Deploy job should not do anything with composer file else cache will fail: https://github.com/rtCamp/ci-demo/blob/master/.circleci/config.yml#L75

`save_cache` should be last task after deployment.

**Comment by rahul286** [comment]
@PatelUtkarsh lets ignore CircleCI cache at all for time being. When jobs become lengthier, we will revisit this. 

Also we removed composer for time being.
