### ISSUE TITLE
Compare .env and wp-config and add missing env variables.

### ISSUE THREAD

**Issue by rahulsprajapati** [rtCamp/ci-demo#14]
Add all env variable to [.circleci/.env.travis](https://github.com/rtCamp/ci-demo/blob/ff4be661d3766af31ec6fb63e4a010f9bf796809/.circleci/.env.travis) file with default value or in comment if required. 
wp-config.php template: https://github.com/rtCamp/ci-demo/blob/ff4be661d3766af31ec6fb63e4a010f9bf796809/.circleci/wp-config.php

This is just to show what are the available options for the environment variable. ( can say as a template )

Example: missing `HTTPS` and `BEHIND_REVERSE_PROXY` variables.

**Comment by rahul286** [comment]
I am blocking this issue because of https://github.com/rtCamp/ci-demo/issues/21
