### ISSUE TITLE
Deploy .env file from it's template to server if not exists.

### ISSUE THREAD

**Issue by rahulsprajapati** [rtCamp/ci-demo#15]
The current [.circleci/.env.travis](https://github.com/rtCamp/ci-demo/blob/master/.circleci/.env.travis) file is used for only test wp installation before final deploy in [.circleci/install_test_wp.sh](https://github.com/rtCamp/ci-demo/blob/master/.circleci/install_test_wp.sh).
https://github.com/rtCamp/ci-demo/blob/6ccf5a59876d49e28f018579f268fa1e9cd3f6d1/.circleci/config.yml#L78

After this the `.env` file is deleted
https://github.com/rtCamp/ci-demo/blob/d6c3c99bf0c49c792afadc4ff1cbc831b4a92119/.circleci/install_test_wp.sh#L29

We need to add this [.circleci/.env.travis](https://github.com/rtCamp/ci-demo/blob/master/.circleci/.env.travis) env for first deployment ( we can simply check if .env file exists or not and create if it's not )

**Comment by PatelUtkarsh** [comment]
It should be called `.env.example` in that case. 
Ref: https://github.com/laravel/laravel/blob/master/.env.example

**Comment by mbtamuli** [comment]
> We need to add this .circleci/.env.travis env for first deployment ( we can simply check if .env file exists or not and create if it's not )

In case it is not clear, @rahulsprajapati is mentioning that this `.env.example` file should be deployed on the server.

**Comment by PatelUtkarsh** [comment]
`.env.travis` is used in a pipeline on CI to test WP setup using `wp eval`. Consider it as a smoke testing.

**Comment by rahulsprajapati** [comment]
I meant `.env` with `.travis` extension and not with `.example` or `.template` extention.

**Comment by rahul286** [comment]
I am blocking this issue because of https://github.com/rtCamp/ci-demo/issues/21
